services:
  ldcgoapi:
    image: landscapedatacommons/ldc-go-api:1.0.0
    build:
      context: .
    logging:
      driver: "json-file"
      options:
        max-file: 3
        max-size: 10m
    ports:
      - "8080:8080" 
    volumes:
      - ./config.yaml:/app/config.yaml:ro  # Bind
    networks:
      - ldc-go-net
networks:
  ldc-go-net:
    external: true